apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitwarden-rs.fullname" . }}
  labels:
    {{- include "bitwarden-rs.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bitwarden-rs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bitwarden-rs.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bitwarden-rs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "bitwarden-rs.fullname" . }}-env
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: ENABLE_DB_WAL
              value: "false"
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: adminToken
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: mysql-password
            - name: DB_HOST
              {{- if .Values.mysql.enabled }}
              value: {{ .Release.Name }}-{{ default "mysql" .Values.mysql.fullnameOverride }}.{{ .Release.Namespace }}
              {{ else }}
              value: {{ .Values.mysql.externalHost }}
              {{- end }}
            - name: DATABASE_URL
              value: "mysql://{{ .Values.mysql.mysqlUser }}:$(DB_PASSWORD)@$(DB_HOST):{{ .Values.mysql.service.port }}/{{ .Values.mysql.mysqlDatabase }}"
            {{- if and .Values.ingress.enabled (.Values.ingress.hosts) }}
            - name: DOMAIN
              value: {{ (index .Values.ingress.hosts 0).host }}
            {{- end }}
            {{- if .Values.credentials.yubicoSecretKey }}
            - name: YUBICO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.credentials.secretName }}
                  key: {{ .Values.credentials.yubicoSecretKey }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 75
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: {{ .Values.bitwardenConfig.data_folder }}

      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "bitwarden-rs.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
